### ISSUE TITLE
Changing Alexa skill to express app

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_alexa_skill#7]
Actual Behaviour
Currently, SUSI Alexa skill uses a serverless lambda function. 

Expected Behaviour
To deploy it to Google container we should make it an express app.

Would you like to work on the issue?
Yes

**Comment by Manveer695** [comment]
I am facing a problem, calling SUSI API in the Alexa skill is not giving correct results. 
<img width="601" alt="alexaskillissue" src="https://user-images.githubusercontent.com/20307535/29397770-33edef94-833e-11e7-8bfb-5c1b7e04fc29.PNG">

Otherwise if I hardcode the answer on the code side, the response is shown correctly. I am working on this issue. Hope to resolve it soon.

**Comment by AliAyub007** [comment]
@Manveer695 If you are using any other package then check Alexa SDK I hope you can solve this problem with this. 
https://www.npmjs.com/package/alexa-sdk
